### ISSUE TITLE
stripInaccessibleToObject, stripInaccessibleToList unit tests fail in v3.2.0

### ISSUE THREAD

**Issue by sjurgis** [beyond-the-cloud-dev/soql-lib#103]
After upgrading from older version (previous version unknown, but older than v2.2.0) I am getting:
```
System.NullPointerException: Attempt to de-reference a null object
Class.SOQL_Test.stripInaccessibleToList: line 2080, column 1
```
I presume because expected exception wasn't throw.
Spring '24 Patch 9.1
Unlimited Edition

In previous version I can see
```
            if (queryException != null) {
```
So perhaps someone modified our copy the lib beforehand...

**Comment by pgajek2** [comment]
Hi @sjurgis,

I checked older versions of SOQL Lib (starting from v2.2.0 and older), and there is no `if (queryException != null)`, so probably someone updated your copy, and I even know why! 👯

## Exmplanation

The `SOQL_Test.stripInaccessibleToList` method is executed in a standard user context. 
By default `Standard User` Profile has **no** access to the `Task.Type` field. 
I assume that access to the `Task.Type` field on your org was granted, and that is fine. 

<img width="917" alt="image" src="https://github.com/beyond-the-cloud-dev/soql-lib/assets/23002099/120461bf-bc66-4b4d-aad9-90bb2d8fab6c">

## Solution 

The `Standard User` Profile on your org has access to the `Task.Type` field, but we need Profile with **no** access to `Task.Type` so `stripInaccessibleToList` will be executed successfully. 

I updated SOQL Lib, so instead of `Standard User` Profile we use `Minimum Access - Salesforce`. It should resolve the problem. 

## Next Step

Please update your SOQL Lib version using code from the `main` branch and let me know if it works as expected.

**Comment by sjurgis** [comment]
Thanks, seems working!
